# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch
rand_tensor = torch.rand(7,7)

# Create random tensor
rand_tensor

tensor([[2.1975e-02, 6.9277e-01, 7.8078e-01, 7.5940e-01, 1.1500e-01, 9.5527e-01,
         2.7800e-01],
        [4.6991e-01, 9.8169e-04, 7.3254e-01, 6.8927e-01, 7.0060e-01, 1.6360e-02,
         4.7382e-01],
        [8.9967e-01, 6.0015e-01, 9.6562e-01, 6.9232e-01, 3.4518e-01, 3.6517e-01,
         2.0992e-01],
        [8.4584e-01, 9.8879e-02, 9.6150e-01, 5.7285e-02, 9.8968e-01, 8.0253e-01,
         7.9200e-01],
        [4.4465e-01, 9.9149e-01, 7.8665e-01, 3.0183e-01, 9.9883e-01, 7.1555e-01,
         3.0168e-02],
        [1.1387e-01, 8.5164e-01, 3.5267e-01, 1.0057e-01, 3.2757e-01, 7.5574e-01,
         1.3153e-01],
        [5.0070e-01, 1.4743e-01, 1.8569e-02, 2.7506e-01, 2.7654e-01, 3.5362e-01,
         6.3653e-01]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
rand_tensor2 = torch.rand(1,7)
rand_tensor2_transpose = rand_tensor2.T

# Perform matrix multiplication 
mul_tensor1 = torch.mm(rand_tensor2, rand_tensor)
mul_tensor2 = torch.mm(rand_tensor, rand_tensor2_transpose)

rand_tensor2, mul_tensor1, mul_tensor2

(tensor([[0.6007, 0.6851, 0.7701, 0.2750, 0.8266, 0.1088, 0.5110]]),
 tensor([[1.8964, 1.8938, 2.6771, 1.8783, 2.0897, 1.9414, 1.2356]]),
 tensor([[1.6390],
         [1.8597],
         [2.3180],
         [2.6422],
         [2.5541],
         [1.3714],
         [1.0841]]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [16]:
# Set manual seed
MANUAL_SEED = 0
torch.manual_seed(seed=MANUAL_SEED)
# Create two random tensors
tensor1 = torch.rand(size=(7,7))

# torch.manual_seed(seed=MANUAL_SEED)
tensor2 = torch.rand(size=(1,7))
# Matrix multiply tensors
mul_tensor = torch.mm(tensor1, tensor2.T)

tensor1, tensor2, mul_tensor, mul_tensor.shape

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]),
 tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [17]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [20]:
# Set random seed
torch.manual_seed(1234)


# Check for access to GPU
if torch.cuda.is_available():
    device = "cuda"
else: device = "cpu"
    
# Create two random tensors on GPU
tensor1 = torch.rand(size=(2,3)).to(device=device)
tensor2 = torch.rand(size=(2,3)).to(device=device)

tensor1, tensor2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [19]:
# Perform matmul on tensor_A and tensor_B
tens_mul = torch.mm(tensor1, tensor2.T)

tens_mul

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max = torch.max(tens_mul)
# Find min
min = torch.min(tens_mul)

max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [26]:
# Find arg max
max_arg = torch.argmax(tens_mul)

# Find arg min
min_arg = torch.argmin(tens_mul) 

max_arg, min_arg

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [28]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_unsqz = torch.rand(size=(1,1,1,10))

# Remove single dimensions
tensor_sqz = torch.squeeze(tensor_unsqz)

# Print out tensors and their shapes
tensor_unsqz, tensor_unsqz.shape, tensor_sqz, tensor_sqz.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))